# Generated by Django 4.1.3 on 2022-11-22 18:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceState',
            fields=[
                ('id_device', models.IntegerField(primary_key=True, serialize=False)),
                ('slot_active', models.BooleanField(default=False)),
                ('LED_state', models.BooleanField(default=False)),
                ('id_slot', models.IntegerField()),
                ('parking_segment', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceHistoric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_slot', models.IntegerField()),
                ('parking_segment', models.CharField(max_length=1)),
                ('busy', models.BooleanField(default=False)),
                ('id_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_historic', to='JustInTime.devicestate')),
            ],
        ),
    ]
