# Generated by Django 4.1.3 on 2022-11-23 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JustInTime', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicehistoric',
            old_name='busy',
            new_name='arrive_leave',
        ),
        migrations.RenameField(
            model_name='devicestate',
            old_name='LED_state',
            new_name='slot_state',
        ),
        migrations.RemoveField(
            model_name='devicehistoric',
            name='id_slot',
        ),
        migrations.RemoveField(
            model_name='devicehistoric',
            name='parking_segment',
        ),
        migrations.RemoveField(
            model_name='devicestate',
            name='id_slot',
        ),
        migrations.RemoveField(
            model_name='devicestate',
            name='slot_active',
        ),
    ]
