# Generated by Django 4.1.3 on 2022-11-25 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JustInTime', '0002_rename_busy_devicehistoric_arrive_leave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupied', models.IntegerField(default=0)),
                ('parking_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_segment', to='JustInTime.devicestate')),
            ],
        ),
    ]
