# Generated by Django 4.1.3 on 2022-11-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JustInTime', '0003_segmentstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentstate',
            name='occupied',
            field=models.FloatField(default=0.0),
        ),
    ]
