# Generated by Django 4.1.3 on 2022-11-27 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JustInTime', '0004_alter_segmentstate_occupied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicehistoric',
            old_name='fecha',
            new_name='hour_date',
        ),
    ]
