# Generated by Django 4.1.3 on 2022-11-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JustInTime', '0005_rename_fecha_devicehistoric_hour_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segmentstate',
            name='id',
        ),
        migrations.AlterField(
            model_name='segmentstate',
            name='parking_segment',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
    ]
