# Generated by Django 4.1.3 on 2022-11-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JustInTime', '0006_remove_segmentstate_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicehistoric',
            name='id_device',
            field=models.IntegerField(),
        ),
    ]
