# Generated by Django 4.1.3 on 2022-11-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JustInTime', '0007_alter_devicehistoric_id_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicehistoric',
            name='id',
        ),
        migrations.AddField(
            model_name='devicehistoric',
            name='parking_segment',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='devicehistoric',
            name='id_device',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
